//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ITNVPluginPlayMsg.ITNVPlayMsgManager {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ITNVPlayMsgManagerSoap", Namespace="http://tempuri.org/")]
    public partial class ITNVPlayMsgManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpenSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpenSessionWOConferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback PlayMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetControlDictionaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendToHuntsDicOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLinesStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHuntsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeLineStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearControlDictionaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHuntInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ITNVPlayMsgManager() {
            this.Url = global::ITNVPluginPlayMsg.Properties.Settings.Default.ITNVPluginPlayMsg_ITNVPlayMsgManager_ITNVPlayMsgManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public ITNVPlayMsgManager(string url)
        {
            this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VersionCompletedEventHandler VersionCompleted;
        
        /// <remarks/>
        public event OpenSessionCompletedEventHandler OpenSessionCompleted;
        
        /// <remarks/>
        public event OpenSessionWOConferenceCompletedEventHandler OpenSessionWOConferenceCompleted;
        
        /// <remarks/>
        public event PlayMessageCompletedEventHandler PlayMessageCompleted;
        
        /// <remarks/>
        public event CloseSessionCompletedEventHandler CloseSessionCompleted;
        
        /// <remarks/>
        public event GetMessageCompletedEventHandler GetMessageCompleted;
        
        /// <remarks/>
        public event ChangeMessageCompletedEventHandler ChangeMessageCompleted;
        
        /// <remarks/>
        public event GetControlDictionaryCompletedEventHandler GetControlDictionaryCompleted;
        
        /// <remarks/>
        public event SendToHuntsDicCompletedEventHandler SendToHuntsDicCompleted;
        
        /// <remarks/>
        public event GetLinesStatusCompletedEventHandler GetLinesStatusCompleted;
        
        /// <remarks/>
        public event GetHuntsCompletedEventHandler GetHuntsCompleted;
        
        /// <remarks/>
        public event ChangeLineStatusCompletedEventHandler ChangeLineStatusCompleted;
        
        /// <remarks/>
        public event ClearControlDictionaryCompletedEventHandler ClearControlDictionaryCompleted;
        
        /// <remarks/>
        public event GetHuntInfoCompletedEventHandler GetHuntInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Version", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Version() {
            object[] results = this.Invoke("Version", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionAsync() {
            this.VersionAsync(null);
        }
        
        /// <remarks/>
        public void VersionAsync(object userState) {
            if ((this.VersionOperationCompleted == null)) {
                this.VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionOperationCompleted);
            }
            this.InvokeAsync("Version", new object[0], this.VersionOperationCompleted, userState);
        }
        
        private void OnVersionOperationCompleted(object arg) {
            if ((this.VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionCompleted(this, new VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpenSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OpenSession(string source, string ivrnumber, string message, string language) {
            object[] results = this.Invoke("OpenSession", new object[] {
                        source,
                        ivrnumber,
                        message,
                        language});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OpenSessionAsync(string source, string ivrnumber, string message, string language) {
            this.OpenSessionAsync(source, ivrnumber, message, language, null);
        }
        
        /// <remarks/>
        public void OpenSessionAsync(string source, string ivrnumber, string message, string language, object userState) {
            if ((this.OpenSessionOperationCompleted == null)) {
                this.OpenSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpenSessionOperationCompleted);
            }
            this.InvokeAsync("OpenSession", new object[] {
                        source,
                        ivrnumber,
                        message,
                        language}, this.OpenSessionOperationCompleted, userState);
        }
        
        private void OnOpenSessionOperationCompleted(object arg) {
            if ((this.OpenSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpenSessionCompleted(this, new OpenSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpenSessionWOConference", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OpenSessionWOConference(string source, string message, string language) {
            object[] results = this.Invoke("OpenSessionWOConference", new object[] {
                        source,
                        message,
                        language});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OpenSessionWOConferenceAsync(string source, string message, string language) {
            this.OpenSessionWOConferenceAsync(source, message, language, null);
        }
        
        /// <remarks/>
        public void OpenSessionWOConferenceAsync(string source, string message, string language, object userState) {
            if ((this.OpenSessionWOConferenceOperationCompleted == null)) {
                this.OpenSessionWOConferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpenSessionWOConferenceOperationCompleted);
            }
            this.InvokeAsync("OpenSessionWOConference", new object[] {
                        source,
                        message,
                        language}, this.OpenSessionWOConferenceOperationCompleted, userState);
        }
        
        private void OnOpenSessionWOConferenceOperationCompleted(object arg) {
            if ((this.OpenSessionWOConferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpenSessionWOConferenceCompleted(this, new OpenSessionWOConferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PlayMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PlayMessage(string source, string message, string language) {
            object[] results = this.Invoke("PlayMessage", new object[] {
                        source,
                        message,
                        language});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PlayMessageAsync(string source, string message, string language) {
            this.PlayMessageAsync(source, message, language, null);
        }
        
        /// <remarks/>
        public void PlayMessageAsync(string source, string message, string language, object userState) {
            if ((this.PlayMessageOperationCompleted == null)) {
                this.PlayMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPlayMessageOperationCompleted);
            }
            this.InvokeAsync("PlayMessage", new object[] {
                        source,
                        message,
                        language}, this.PlayMessageOperationCompleted, userState);
        }
        
        private void OnPlayMessageOperationCompleted(object arg) {
            if ((this.PlayMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PlayMessageCompleted(this, new PlayMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CloseSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CloseSession(string source) {
            object[] results = this.Invoke("CloseSession", new object[] {
                        source});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CloseSessionAsync(string source) {
            this.CloseSessionAsync(source, null);
        }
        
        /// <remarks/>
        public void CloseSessionAsync(string source, object userState) {
            if ((this.CloseSessionOperationCompleted == null)) {
                this.CloseSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseSessionOperationCompleted);
            }
            this.InvokeAsync("CloseSession", new object[] {
                        source}, this.CloseSessionOperationCompleted, userState);
        }
        
        private void OnCloseSessionOperationCompleted(object arg) {
            if ((this.CloseSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseSessionCompleted(this, new CloseSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessage(string source) {
            object[] results = this.Invoke("GetMessage", new object[] {
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageAsync(string source) {
            this.GetMessageAsync(source, null);
        }
        
        /// <remarks/>
        public void GetMessageAsync(string source, object userState) {
            if ((this.GetMessageOperationCompleted == null)) {
                this.GetMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageOperationCompleted);
            }
            this.InvokeAsync("GetMessage", new object[] {
                        source}, this.GetMessageOperationCompleted, userState);
        }
        
        private void OnGetMessageOperationCompleted(object arg) {
            if ((this.GetMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageCompleted(this, new GetMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangeMessage(string phone, string message) {
            this.Invoke("ChangeMessage", new object[] {
                        phone,
                        message});
        }
        
        /// <remarks/>
        public void ChangeMessageAsync(string phone, string message) {
            this.ChangeMessageAsync(phone, message, null);
        }
        
        /// <remarks/>
        public void ChangeMessageAsync(string phone, string message, object userState) {
            if ((this.ChangeMessageOperationCompleted == null)) {
                this.ChangeMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeMessageOperationCompleted);
            }
            this.InvokeAsync("ChangeMessage", new object[] {
                        phone,
                        message}, this.ChangeMessageOperationCompleted, userState);
        }
        
        private void OnChangeMessageOperationCompleted(object arg) {
            if ((this.ChangeMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetControlDictionary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetControlDictionary() {
            object[] results = this.Invoke("GetControlDictionary", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetControlDictionaryAsync() {
            this.GetControlDictionaryAsync(null);
        }
        
        /// <remarks/>
        public void GetControlDictionaryAsync(object userState) {
            if ((this.GetControlDictionaryOperationCompleted == null)) {
                this.GetControlDictionaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetControlDictionaryOperationCompleted);
            }
            this.InvokeAsync("GetControlDictionary", new object[0], this.GetControlDictionaryOperationCompleted, userState);
        }
        
        private void OnGetControlDictionaryOperationCompleted(object arg) {
            if ((this.GetControlDictionaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetControlDictionaryCompleted(this, new GetControlDictionaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendToHuntsDic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendToHuntsDic(string hd) {
            object[] results = this.Invoke("SendToHuntsDic", new object[] {
                        hd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendToHuntsDicAsync(string hd) {
            this.SendToHuntsDicAsync(hd, null);
        }
        
        /// <remarks/>
        public void SendToHuntsDicAsync(string hd, object userState) {
            if ((this.SendToHuntsDicOperationCompleted == null)) {
                this.SendToHuntsDicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendToHuntsDicOperationCompleted);
            }
            this.InvokeAsync("SendToHuntsDic", new object[] {
                        hd}, this.SendToHuntsDicOperationCompleted, userState);
        }
        
        private void OnSendToHuntsDicOperationCompleted(object arg) {
            if ((this.SendToHuntsDicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendToHuntsDicCompleted(this, new SendToHuntsDicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLinesStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLinesStatus() {
            object[] results = this.Invoke("GetLinesStatus", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLinesStatusAsync() {
            this.GetLinesStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetLinesStatusAsync(object userState) {
            if ((this.GetLinesStatusOperationCompleted == null)) {
                this.GetLinesStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLinesStatusOperationCompleted);
            }
            this.InvokeAsync("GetLinesStatus", new object[0], this.GetLinesStatusOperationCompleted, userState);
        }
        
        private void OnGetLinesStatusOperationCompleted(object arg) {
            if ((this.GetLinesStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLinesStatusCompleted(this, new GetLinesStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHunts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHunts() {
            object[] results = this.Invoke("GetHunts", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHuntsAsync() {
            this.GetHuntsAsync(null);
        }
        
        /// <remarks/>
        public void GetHuntsAsync(object userState) {
            if ((this.GetHuntsOperationCompleted == null)) {
                this.GetHuntsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHuntsOperationCompleted);
            }
            this.InvokeAsync("GetHunts", new object[0], this.GetHuntsOperationCompleted, userState);
        }
        
        private void OnGetHuntsOperationCompleted(object arg) {
            if ((this.GetHuntsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHuntsCompleted(this, new GetHuntsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeLineStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeLineStatus(string line, int status) {
            object[] results = this.Invoke("ChangeLineStatus", new object[] {
                        line,
                        status});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeLineStatusAsync(string line, int status) {
            this.ChangeLineStatusAsync(line, status, null);
        }
        
        /// <remarks/>
        public void ChangeLineStatusAsync(string line, int status, object userState) {
            if ((this.ChangeLineStatusOperationCompleted == null)) {
                this.ChangeLineStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeLineStatusOperationCompleted);
            }
            this.InvokeAsync("ChangeLineStatus", new object[] {
                        line,
                        status}, this.ChangeLineStatusOperationCompleted, userState);
        }
        
        private void OnChangeLineStatusOperationCompleted(object arg) {
            if ((this.ChangeLineStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeLineStatusCompleted(this, new ChangeLineStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearControlDictionary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ClearControlDictionary() {
            object[] results = this.Invoke("ClearControlDictionary", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ClearControlDictionaryAsync() {
            this.ClearControlDictionaryAsync(null);
        }
        
        /// <remarks/>
        public void ClearControlDictionaryAsync(object userState) {
            if ((this.ClearControlDictionaryOperationCompleted == null)) {
                this.ClearControlDictionaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearControlDictionaryOperationCompleted);
            }
            this.InvokeAsync("ClearControlDictionary", new object[0], this.ClearControlDictionaryOperationCompleted, userState);
        }
        
        private void OnClearControlDictionaryOperationCompleted(object arg) {
            if ((this.ClearControlDictionaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearControlDictionaryCompleted(this, new ClearControlDictionaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHuntInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HuntInfo GetHuntInfo(string hunt) {
            object[] results = this.Invoke("GetHuntInfo", new object[] {
                        hunt});
            return ((HuntInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetHuntInfoAsync(string hunt) {
            this.GetHuntInfoAsync(hunt, null);
        }
        
        /// <remarks/>
        public void GetHuntInfoAsync(string hunt, object userState) {
            if ((this.GetHuntInfoOperationCompleted == null)) {
                this.GetHuntInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHuntInfoOperationCompleted);
            }
            this.InvokeAsync("GetHuntInfo", new object[] {
                        hunt}, this.GetHuntInfoOperationCompleted, userState);
        }
        
        private void OnGetHuntInfoOperationCompleted(object arg) {
            if ((this.GetHuntInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHuntInfoCompleted(this, new GetHuntInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HuntInfo {
        
        private int totalField;
        
        private int freeField;
        
        /// <remarks/>
        public int total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public int free {
            get {
                return this.freeField;
            }
            set {
                this.freeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void VersionCompletedEventHandler(object sender, VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void OpenSessionCompletedEventHandler(object sender, OpenSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpenSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpenSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void OpenSessionWOConferenceCompletedEventHandler(object sender, OpenSessionWOConferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpenSessionWOConferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpenSessionWOConferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PlayMessageCompletedEventHandler(object sender, PlayMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlayMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PlayMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CloseSessionCompletedEventHandler(object sender, CloseSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetMessageCompletedEventHandler(object sender, GetMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ChangeMessageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetControlDictionaryCompletedEventHandler(object sender, GetControlDictionaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetControlDictionaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetControlDictionaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SendToHuntsDicCompletedEventHandler(object sender, SendToHuntsDicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendToHuntsDicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendToHuntsDicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetLinesStatusCompletedEventHandler(object sender, GetLinesStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLinesStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLinesStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetHuntsCompletedEventHandler(object sender, GetHuntsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHuntsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHuntsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ChangeLineStatusCompletedEventHandler(object sender, ChangeLineStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeLineStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeLineStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ClearControlDictionaryCompletedEventHandler(object sender, ClearControlDictionaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearControlDictionaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClearControlDictionaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetHuntInfoCompletedEventHandler(object sender, GetHuntInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHuntInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHuntInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HuntInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HuntInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591